name: 'Push into Live / Deployment'
on:
  push:
    branches: [live]
  workflow_dispatch:

concurrency:
  group: deployment
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Get Required NodeJS Version via .nvmrc'
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: 'Install, build, and upload site'
        uses: withastro/action@v3
        with:
          node-version: ${{ env.NVMRC }}

  deploy:
    name: 'Deploy'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4
